"""add organization to locations

Revision ID: 7bf08015ba42
Revises: 0dc9f4f2a125
Create Date: 2026-09-04 12:23:19.854595

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7bf08015ba42'
down_revision: Union[str, Sequence[str], None] = '0dc9f4f2a125'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('locations', sa.Column('organization_id', sa.UUID(), nullable=False))
    op.create_index(op.f('ix_locations_organization_id'), 'locations', ['organization_id'], unique=False)
    op.create_foreign_key(None, 'locations', 'organizations', ['organization_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'locations', type_='foreignkey')
    op.drop_index(op.f('ix_locations_organization_id'), table_name='locations')
    op.drop_column('locations', 'organization_id')
    # ### end Alembic commands ###
